config/routes.rb
Rails.application.routes.draw do
  root "dashboard#dashboard"

  resources :short_url_requests do
    member do
      post "accept" => "short_url_requests#accept"
      get "new_rejection" => "short_url_requests#new_rejection"
      get "remove" => "short_url_requests#remove"
      post "reject" => "short_url_requests#reject"
    end
  end
  get "list_short_urls" => "short_url_requests#list_short_urls"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::Mongoid,
    GovukHealthcheck::SidekiqRedis,
  )

  mount GovukPublishingComponents::Engine, at: "/component-guide"
  get "/styleguide" => "govuk_admin_template/style_guide#index"
end

app/views/notifier/short_url_request_accepted.text.erb
Dear <%= @short_url_request.requester.name %>,

Your request for a short URL has been accepted and is now live. The path at <%= @short_url_request.redirect.from_path %> now redirects to <%= @short_url_request.redirect.to_path %>.

app/views/notifier/short_url_request_rejected.text.erb
Dear <%= @short_url_request.requester.name %>,

Your request for a short URL from <%= @short_url_request.from_path %> to <%= @short_url_request.to_path %> has been denied.

<% if @short_url_request.rejection_reason.present? %>
The following reason was given:
<%= @short_url_request.rejection_reason %>
<% else %>
No reason was given.
<% end %>

app/views/notifier/short_url_requested.text.erb
Short URL request for '<%= @short_url_request.from_path %>' by <%= @short_url_request.organisation_title %>


From:
<%= @short_url_request.from_path %>

To:
<%= @short_url_request.to_path %>

Requester:
<%= @short_url_request.requester.name %>

Contact email:
<%= @short_url_request.contact_email %>

Organisation:
<%= @short_url_request.organisation_title %>

Reason:
<%= @short_url_request.reason %>

You can respond to this request here:
<%= short_url_manger_url_for(short_url_request_url(@short_url_request, only_path: true)) %>