config/routes.rb
Rails.application.routes.draw do
  root "dashboard#dashboard"

  resources :short_url_requests do
    member do
      post "accept" => "short_url_requests#accept"
      get "new_rejection" => "short_url_requests#new_rejection"
      get "remove" => "short_url_requests#remove"
      post "reject" => "short_url_requests#reject"
    end
  end
  get "list_short_urls" => "short_url_requests#list_short_urls"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::Mongoid,
    GovukHealthcheck::SidekiqRedis,
  )

  mount GovukPublishingComponents::Engine, at: "/component-guide"
  get "/styleguide" => "govuk_admin_template/style_guide#index"
end

app/models/short_url_request.rb
class ShortUrlRequest
  include GlobalID::Identification
  include Mongoid::Document
  include Mongoid::Timestamps
  include ShortUrlValidations

  field :state, type: String, default: "pending"
  field :from_path, type: String
  field :to_path, type: String
  field :route_type, type: String, default: "exact"
  field :segments_mode, type: String, default: "ignore"
  field :override_existing, type: Boolean, default: false
  field :reason, type: String
  field :contact_email, type: String
  field :organisation_slug, type: String
  field :organisation_title, type: String
  field :rejection_reason, type: String

  belongs_to :requester, class_name: "User", optional: true
  has_one :redirect, dependent: :destroy

  validates :state, :reason, :contact_email, :organisation_slug, :organisation_title, presence: true
  validates :state, inclusion: { in: %w[pending accepted rejected superseded] }, allow_blank: true
  validate :not_already_live

  before_validation :retrieve_organisation_title, if: -> { organisation_slug_changed? }
  before_validation :strip_whitespace, only: %i[from_path to_path]

  scope :pending, -> { where(state: "pending") }
  scope :accepted, -> { where(state: "accepted") }

  attr_accessor :confirmed

  def similar_redirects
    @similar_redirects ||= Redirect.or({ from_path: }, to_path:)
  end

  def similar_requests
    @similar_requests ||= ShortUrlRequest.where(from_path:, :id.ne => id).order_by(%i[created_at asc])
  end

  def pending?
    state == "pending"
  end

  def accepted?
    state == "accepted"
  end

  def rejected?
    state == "rejected"
  end

  def superseded?
    state == "superseded"
  end

  def uses_advanced_options?
    route_type != "exact" || segments_mode != "ignore"
  end

private

  def not_already_live
    if Redirect
         .where(
           :from_path => from_path,
           :to_path => to_path,
           :route_type => route_type,
           :segments_mode => segments_mode,
           :override_existing => override_existing,
           :short_url_request.ne => self,
         )
         .exists?
      errors.add(:base, "The specified Short URL already redirects to the specified Target URL")
      false
    end
  end

  def retrieve_organisation_title
    self.organisation_title = Organisation.find_by(slug: organisation_slug).try(:title)
  end

  def strip_whitespace
    self.from_path = from_path.strip
    self.to_path = to_path.strip
  end
end

app/controllers/short_url_requests_controller.rb
class ShortUrlRequestsController < ApplicationController
  before_action :authorise_as_short_url_requester!, only: %i[new create]
  before_action :authorise_as_short_url_manager!, only: %i[index show accept new_rejection reject list_short_urls edit update destroy remove]
  before_action :get_short_url_request, only: %i[edit update show accept new_rejection reject destroy remove]

  def index
    @short_url_requests = ShortUrlRequest.pending.order_by([:created_at, "desc"]).paginate(page: params[:page], per_page: 40)
  end

  def show
    @existing_redirect = Redirect.where(from_path: @short_url_request.from_path).first
  end

  def list_short_urls
    @accepted_short_urls = ShortUrlRequest.accepted.order_by([:created_at, "desc"])
  end

  def new
    @short_url_request = ShortUrlRequest.new(organisation_slug: current_user.organisation_slug)
  end

  def create
    Commands::ShortUrlRequests::Create.new(create_short_url_request_params, current_user).call(
      success: lambda { |_url_request|
        flash[:success] = "Your request has been made."
        redirect_to root_path
      },
      failure: lambda { |url_request|
        @short_url_request = url_request
        render "new"
      },
      confirmation_required: lambda { |url_request|
        @short_url_request = url_request
        render "confirmation"
      },
    )
  end

  def accept
    if @short_url_request.uses_advanced_options?
      authorise_user!("advanced_options")
    end

    Commands::ShortUrlRequests::Accept.new(@short_url_request).call(
      failure: -> { render "short_url_requests/accept_failed" },
    )
  end

  def new_rejection; end

  def reject
    rejection_params = params.require(:short_url_request).permit(:rejection_reason)
    Commands::ShortUrlRequests::Reject.new(@short_url_request, rejection_params[:rejection_reason]).call
    flash[:success] = "The short URL request has been rejected, and the requester has been notified."

    redirect_to short_url_requests_path
  end

  def edit; end

  def update
    Commands::ShortUrlRequests::Update.new(update_short_url_request_params, @short_url_request).call(
      success: lambda {
        flash[:success] = "Your edit was successful."
        redirect_to short_url_request_path(@short_url_request)
      },
      failure: lambda {
        # flash[:alert] = "Bah humbug."
        render "edit"
      },
    )
  end

  def remove; end

  def destroy
    Commands::ShortUrlRequests::Destroy.new(get_short_url_request).call(
      success: lambda {
        flash.notice = "Short URL #{get_short_url_request.from_path} was deleted."
      },
      failure: lambda {
        flash.alert = "Failed to delete Short URL #{get_short_url_request.from_path}."
      },
    )
    redirect_to short_url_requests_path
  end

  def organisations
    @organisations ||= Organisation.all.order_by([:title, "asc"])
  end
  helper_method :organisations

protected

  def allow_use_of_advanced_options?
    current_user.has_permission? "advanced_options"
  end
  helper_method :allow_use_of_advanced_options?

  def allow_accepting_request?
    return true unless @short_url_request.uses_advanced_options?

    allow_use_of_advanced_options?
  end
  helper_method :allow_accepting_request?

private

  def get_short_url_request
    @short_url_request ||= ShortUrlRequest.find(params[:id])
  rescue Mongoid::Errors::DocumentNotFound
    render plain: "Not found", status: :not_found
  end

  def create_short_url_request_params
    params[:short_url_request].permit(:from_path, :to_path, :reason, :route_type, :segments_mode, :organisation_slug, :override_existing, :confirmed)
  end

  def update_short_url_request_params
    params[:short_url_request].permit(:to_path, :reason, :route_type, :segments_mode, :override_existing, :organisation_slug)
  end
end

app/views/short_url_requests/_existing_redirect.html.erb
<%= render "govuk_publishing_components/components/warning_text", {
  text: "#{existing_redirect.from_path} already redirects to #{existing_redirect.to_path}! Accepting this request will overwrite
  that."
} %>

app/views/short_url_requests/_form.html.erb
<%= form_for @short_url_request do |f| %>
  <dl>
    <dt>State:</dt>
    <dd><%= @short_url_request.state.titleize %></dd>
  </dl>
  <%= render_errors_for @short_url_request, leading_message: "Your request for a URL redirect or short URL could not be made for the following reasons:" %>
  <fieldset>
    <div class="form-group">
      <%= f.label :from_path %>
      <%= f.text_field :from_path, disabled: @short_url_request.persisted?, class: 'form-control input-md-8' %>
      <p class="help-block">This is the URL or the short URL to redirect the user from. Please specify it as a relative path (eg. "/hmrc/tax-evasion").</p>
    </div>

    <div class="form-group">
      <%= f.label :to_path %>
      <%= f.text_field :to_path, class: 'form-control input-md-8' %>
      <p class="help-block">This is the URL to redirect the user to. The following types of target URL are supported:</p>
      <ul class="help-block">
        <li>Internal gov.uk links, eg. <strong>/government/publications/what-hmrc-does-to-prevent-tax-evasion</strong></li>
        <li>External gov.uk subdomain links, eg. <strong>https://my-title.external.gov.uk/an-optional-path</strong></li>
        <li>External government subdomain links, eg. <strong><%= ShortUrlValidations.allow_host_display_list %></strong></li>
      </ul>
    </div>

    <div class="form-group">
      <%= f.label :organisation_slug %>
      <%= f.select :organisation_slug, options_for_select(organisations.map {|org| [org.title, org.slug] }, @short_url_request.organisation_slug), {}, class: 'form-control input-md-6' %>
    </div>

    <div class="form-group">
      <%= f.label :reason %>
      <%= f.text_area :reason, class: 'form-control input-md-8' %>
      <p class="help-block">Please explain the reason for this request, as requests without a clear and valid reason will be denied. Include any Zendesk ticket URL or other information if available.</p>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group">
      <% if @short_url_request.new_record? %>
        <%= f.submit "Submit request", class: 'btn btn-success' %>
        <%= link_to "Cancel", '/', class: "btn btn-default add-left-margin" %>
      <% else %>
        <%= f.submit "Update", class: 'btn btn-success' %>
        <%= link_to "Cancel", short_url_request_path(@short_url_request), class: "btn btn-default add-left-margin" %>
      <% end %>
    </div>
  </fieldset>

  <% if allow_use_of_advanced_options? %>
  <fieldset>
    <h2>Advanced options</h2>
    <p>Leave as defaults if unsure.</p>
    <div class="form-group">
      <%= f.label :override_existing %>
      <%= f.select :override_existing, options_for_select({ "No" => false, "Yes" => true }, @short_url_request.override_existing), {}, class: 'form-control input-md-6' %>
      <p>This will allow the redirect to override any existing content for this path. Be <strong>very careful</strong> with this option.</p>
    </div>
    <div class="form-group">
      <%= f.label :route_type, 'From redirects' %>
      <%= f.select :route_type, options_for_select({ "Exact URL only" => "exact", "URL and all pages under it" => "prefix" }, @short_url_request.route_type), {}, class: 'form-control input-md-6' %>
      <p>Do not redirect all pages unless you need any page with an address which starts with your input to also be redirected. For example, if you add <strong>gov.uk/address/</strong> then <strong>gov.uk/address/gone</strong> would also be redirected.</p>
    </div>

    <div class="form-group">
      <%= f.label :segments_mode, 'Segments' %>
      <%= f.select :segments_mode, options_for_select({ "Discard" => "ignore", "Keep" => "preserve" }, @short_url_request.segments_mode), {}, class: 'form-control input-md-6' %>
    </div>

    <h3>Help with Segments</h3>
    <h4>Discard</h4>
    <h5>Using "Exact URL only"</h5>
    <p>For source <strong>/from?q=123</strong> and target url <strong>/target</strong> will redirect to <strong>/target</strong></p>
    <h5>Using "URL and all pages under it"</h5>
    <p>For source <strong>/from?q=123</strong> and target url <strong>/target</strong> will redirect to <strong>/target</strong> and also <strong>/from/doe/a/deer</strong> will redirect to <strong>/target</strong></p>


    <h4>Keep</h4>
    <h5>Using "Exact URL only"</h5>
    <p>For source <strong>/from/?q=123</strong> and target url <strong>/target</strong> will redirect to <strong>/target?q=123</strong></p>
    <h5>Using "URL and all pages under it"</h5>
    <p>For source <strong>/from/?q=123</strong> and target url <strong>/target</strong> will redirect to <strong>/target/page/?q=123</strong> and also <strong>/from/doe/a/deer</strong> will redirect to <strong>/target/doe/a/deer</strong></p>

  </fieldset>
  <% end %>
<%- end -%>

app/views/short_url_requests/_short_url_request.html.erb
<tr class="clickable-row">
  <td><%= link_to short_url_request.organisation_title, short_url_request_path(short_url_request) %></td>
  <td><%= link_to short_url_request.from_path, short_url_request_path(short_url_request) %></td>
  <td><%= link_to short_url_request.to_path, short_url_request_path(short_url_request) %></td>
</tr>

app/views/short_url_requests/_short_url_request_data.html.erb
<dl>
  <dt>By:</dt>
  <dd><%= short_url_request.organisation_title %></dd>

  <dt>Requested at:</dt>
  <dd><%= short_url_request.created_at.to_fs(:govuk_date) %></dd>

  <% if show_short_url %>
    <dt>URL redirect or short URL:</dt>
    <dd><%= short_url_request.from_path %></dd>
  <% end %>

  <dt>Target URL:</dt>
  <dd><%= link_to short_url_request.to_path, govuk_url_for(short_url_request.to_path) %></dd>

  <dt>Override existing:</dt>
  <dd><%= short_url_request.override_existing? ? "Yes" : "No" %></dd>

  <dt>Route type:</dt>
  <dd><%= short_url_request.route_type %></dd>

  <dt>Segments mode:</dt>
  <dd><%= short_url_request.segments_mode %></dd>

  <dt>Reason:</dt>
  <dd><%= short_url_request.reason %></dd>

  <dt>Contact email:</dt>
  <dd><%= short_url_request.contact_email %></dd>

  <dt>State:</dt>
  <dd><%= short_url_request.state.titleize %></dd>
</dl>

app/views/short_url_requests/accept.html.erb
<% breadcrumb :short_url_request_accepted, @short_url_request %>

<h1>The redirect has been published</h1>

<dl>
  <dt>From:</dt>
  <dd><%= link_to @short_url_request.redirect.from_path, govuk_url_for(@short_url_request.redirect.from_path) %></dd>

  <dt>To:</dt>
  <dd><%= link_to @short_url_request.redirect.to_path, govuk_url_for(@short_url_request.redirect.to_path) %></dd>
</dl>

<%= link_to "Done", short_url_requests_path, class: "btn btn-default" %>

app/views/short_url_requests/accept_failed.html.erb
<% breadcrumb :short_url_request_accepted_failed, @short_url_request %>

<h1>The redirect could not be published</h1>

<%= render_errors_for @short_url_request.redirect, leading_message: "The URL redirect or short URL could not be created for the following reasons:" %>

app/views/short_url_requests/confirmation.html.erb
<%= form_for @short_url_request do |f| %>
  <%= f.hidden_field :from_path %>
  <%= f.hidden_field :to_path %>
  <%= f.hidden_field :organisation_slug %>
  <%= f.hidden_field :reason %>
  <%= f.hidden_field :confirmed, value: true %>
  <% if allow_use_of_advanced_options? %>
    <%= f.hidden_field :override_existing %>
    <%= f.hidden_field :route_type %>
    <%= f.hidden_field :segments_mode %>
  <% end %>
  <% if would_overwrite_existing?(@short_url_request) %>
    <h1>Redirects for that URL redirect or short URL already exist!</h1>
  <% else %>
    <h1>A URL redirect or short URL already redirects to that content</h1>
  <% end %>
  <p>These URL redirects or short URLs are already live on GOV.UK:</p>
  <ul>
    <% @short_url_request.similar_redirects.each do |dupe| %>
      <li>
        <code><%= dupe.from_path %></code> redirecting to <code><%= dupe.to_path %></code>
      </li>
    <% end %>
  </ul>
  <p>
    You requested to redirect <code><%= @short_url_request.from_path %></code>
    to <code><%= @short_url_request.to_path %>.</code>
  </p>
  <% if would_overwrite_existing?(@short_url_request) %>
    <p>If your request is accepted, it will overwrite the existing URL redirect or short URL.</p>
  <% else %>
    <p>Do you want another URL redirect or short URL to redirect to that content?</p>
  <% end %>
  <%= f.submit 'Yes, I still want to request this URL redirect or short URL', class: 'btn btn-success' %>
  <%= link_to "Cancel", '/', class: "btn btn-default add-left-margin" %>
<% end %>

app/views/short_url_requests/edit.html.erb
<% breadcrumb :edit_short_url_request, @short_url_request %>

<%= content_for :page_title, 'Edit short URL' %>
  <h1 class="govuk-heading-xl">
    <% if @short_url_request.pending? %>
      Edit URL redirect or short URL request
    <% else %>
      Edit live URL redirect or short URL
    <% end %>
  </h1>

  <%= render :partial => 'form' %>

app/views/short_url_requests/index.html.erb
<h1 class="govuk-heading-xl">URL redirect and short URL requests</h1>

<%= @short_url_requests.inspect %>
<%
  requests_rows = @short_url_requests.map do |request|

  end
%>

<%= render "govuk_publishing_components/components/table", {
  head: [
    {
      text: "Organisation"
    },
    {
      text: "From URL",
    },
    {
      text: "To URL",
    }
  ],
  rows: []
} %>

<table class="table table-bordered table-hover">
  <thead>
    <tr class="table-header">
      <th>Organisation</th>
      <th>From</th>
      <th>To</th>
    </tr>
  </thead>
  <tbody>
    <%= render @short_url_requests %>
  </tbody>
</table>

app/views/short_url_requests/list_short_urls.html.erb
<% breadcrumb :live_short_urls %>

<table class="table table-bordered table-hover" data-module="filterable-table">
  <thead>
    <tr class="table-header">
      <th>Organisation</th>
      <th>From</th>
      <th>To</th>
      <th>State</th>
      <th>Date</th>
    </tr>
    <tr class="if-no-js-hide table-header-secondary">
      <td colspan="5">
        <form>
          <label for="url-list-filter" class="rm">Filter short URLs</label>
          <input id="url-list-filter" type="text" class="form-control normal js-filter-table-input" placeholder="Filter short URLs">
        </form>
      </td>
    </tr>
  </thead>
  <% @accepted_short_urls.each do |request| %>
    <tr class="clickable-row">
      <td><%= link_to request.organisation_title, short_url_request_path(request) %></td>
      <td><%= link_to request.from_path, short_url_request_path(request) %></td>
      <td><%= link_to request.to_path, short_url_request_path(request) %></td>
      <td><%= link_to request.state.titleize, short_url_request_path(request) %></td>
      <td><%= link_to request.updated_at.to_date, short_url_request_path(request) %></td>
    </tr>
  <% end %>
</table>

app/views/short_url_requests/new.html.erb
<h1 class="govuk-heading-xl">Request a new URL redirect or short URL</h1>

<p class="govuk-body">Please read <a href="https://www.gov.uk/guidance/contact-the-government-digital-service/request-a-thing#short-url" class="govuk-link">the guidance on short URL requests</a> before making a request.</p>

<%= render :partial => 'form' %>

app/views/short_url_requests/new_rejection.html.erb
<% breadcrumb :reject_short_url_request, @short_url_request %>

<h1>Reject this URL redirect or short URL request</h1>

<%= render 'short_url_request_data', short_url_request: @short_url_request, show_short_url: true %>

<%= form_for @short_url_request, url: { action: :reject }, method: :post do |f| %>
  <%= render_errors_for @short_url_request, leading_message: "The short URL request could not be rejected for the following reasons:" %>
  <fieldset>
    <div class="form-group">
      <%= f.label :rejection_reason, "Reason" %>
      <%= f.text_area :rejection_reason, class: 'form-control' %>
      <p class="help-block">Optionally, tell the requester why you are rejecting their request.</p>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group">
      <%= f.submit "Reject", class: 'btn btn-danger' %>
    </div>
  </fieldset>
<%- end -%>

app/views/short_url_requests/remove.html.erb
<% breadcrumb :remove_short_url_request, @short_url_request %>

<h1>Delete URL redirect or Short URL <%= @short_url_request.from_path %></h1>

<%= form_for(@short_url_request, html: { method: :delete }) do |f| %>
  <%= render_errors_for @short_url_request, leading_message: "Your submission failed for the following reasons:" %>
  <fieldset>
    <div class="form-group">
      <%= f.submit "Delete", class: 'btn btn-danger' %>
      <%= link_to "Cancel", short_url_request_path(@short_url_request), class: "btn btn-default add-left-margin" %>
    </div>
  </fieldset>
<%- end -%>

app/views/short_url_requests/show.html.erb
<% breadcrumb :short_url_request, @short_url_request %>

<h1>URL redirect or Short URL requested by <%= @short_url_request.organisation_title %></h1>

<% if @short_url_request.state == 'pending' && @existing_redirect.present? %>
  <%= render 'existing_redirect', existing_redirect: @existing_redirect %>
<% end %>

<%= render 'short_url_request_data', short_url_request: @short_url_request, show_short_url: true %>

<div class="panel panel-default other-requests">
  <div class="panel-heading">
    <h2>Other requests for this short URL</h2>
  </div>
  <div class="panel-body">
    <% if @short_url_request.similar_requests.any? %>
      <ol>
        <% @short_url_request.similar_requests.each do |similar_request| %>
          <li><%= render 'short_url_request_data', short_url_request: similar_request, show_short_url: false %></li>
        <% end %>
      </ol>
    <% else %>
      <p>None</p>
    <% end %>
  </div>
</div>

<% unless allow_accepting_request? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h2>You cannot accept this redirect request at the moment</h2>
    </div>
    <div class="panel-body">
      Accepting redirect requests with 'override existing', a type of 'prefix',
      or a segments mode of 'ignore' is currently disabled for most users,
      as this functionality is still being developed.
    </div>
  </div>
<% end %>

<% if @short_url_request.state == 'pending' %>
  <%= button_to "Accept and create redirect", accept_short_url_request_path(@short_url_request), method: :post, class: "btn btn-success add-right-margin", disabled: allow_accepting_request? ? nil : 'disabled' %>
  <%= link_to "Reject", new_rejection_short_url_request_path(@short_url_request), class: "btn btn-danger add-right-margin" %>
<% end %>
<%= link_to "Edit", edit_short_url_request_path, class: "btn btn-default" %>
<%= link_to "Delete", remove_short_url_request_path, class: "btn btn-danger" %>